@startuml

'メソッド名をが遷移に記述'
'コード間のメソッドに引数が必要な時は(型 引数名, )の中に記述'
'モデルの記述'
'データベースは "database データベース名 as usersと記述する '

'タイトルを記述'
title ユーザ作成

'シーケンスの縦線の下部にシーケンスボックスを出すかどうか(hideで出さない)指定する.'
hide footbox

'アクター'
actor User as user

'オブジェクト'
participant View as view
participant CreateController as controller
participant UserService as service
participant UserDao as dao
database sample_gradle as users

'遷移'
user -> view :

activate view
view -> controller :doPost(String name, String pass)

activate controller
controller -> service : create(User user)

activate service
service -> dao :create(User user)

activate dao
dao -> users : 登録

activate users
users -> dao :

deactivate users

dao -> service
deactivate dao

service -> controller
deactivate service

controller ->  view
deactivate controller

@enduml
