@startuml

'メソッド名をが遷移に記述'
'コード間のメソッドに引数が必要な時は(型 引数名, )の中に記述'
'モデルの記述'
'データベースは "database データベース名 as usersと記述する '

'タイトルを記述'
title ユーザ作成

'シーケンスの縦線の下部にシーケンスボックスを出すかどうか(hideで出さない)指定する.'
hide footbox

'アクター'
actor User as user

participant create.jsp as view
participant index.jsp as view2
participant Create as controller
participant UserService as service
participant UsersDao as dao
database sample_gradle as users

'繊維'
user -> view

activate view
view -> controller :post(name, pass)
deactivate view

activate controller
controller -> service :create(user)

activate service
service -> dao :create(user, connection)

activate dao
dao -> users :登録

activate users
users -> dao
deactivate users

dao -> service
deactivate dao

service -> controller
deactivate service

controller ->  view2
deactivate controller

activate view2
view2 -> user
deactivate view2

@enduml
