version: '2' #docker-composeのバージョンを指定
services:
  sample:
    build: . #Dockerfileをビルド
    ports:
    - "5200:8080" #ポート5200番の開放

    privileged: true
    tty: true
    command: /sbin/init

networks:
  default:
    external:
      name: onyx