/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}

	public double tax(double a) {
		return a * 1.08;
	}
}
